# Change these first
owner: realya # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Realya
    url: https://realya.ch/
  - name: CDN
    url: https://cdn.realya.ch/
  - name: CDN1
    url: https://cdn1.realya.ch/
  - name: CDN2
    url: https://cdn2.realya.ch/
  - name: CDN3
    url: https://cdn3.realya.ch/
  - name: CDN4
    url: https://cdn4.realya.ch/

status-website:
  # Add your custom domain name, or remove the cname line if you don't have a domain
  # Uncomment the baseUrl line if you don't have a custom domain and add your repo name there
  cname: status.realya.ch
  # baseUrl: /your-repo-name
  logoUrl: https://realya.ch/assets/img/Logo/favicon.png
  name: Status Realya
  introTitle: "Upptime Titre"
  introMessage: "Un message qui sers d'information."
  navbar:
    - title: Status
      href: /
    - title: Realya
      href: https://realya.ch/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
